### PR TITLE
Link unlink items

### PR DESCRIPTION
**Pull request by domi4484**
Implemented buttons to move features from/to link/unlink lists.

I have added an icon to make clear which items are going to be changed:
- No icon: Unmodified
- Link icon: Feature is going to be linked on accept
- Unlink icon: Feature is going to be unlinked on accept

Maybe just make the text different (like italic or green) for changed features would be less "gui intrusive"

Peek 2022-01-24 07-00

### CODE REVIEW

**Review by signedav — COMMENTED** [review]
Cool.

File structure with the refactoring etc. looks good so far. 

When running it I got some errors, but I suppose you already solved them meanwhile.

Eg.  `feature_list` is not defined. I guess it's `linkedFeatures`.

Another is that it couldn't get the `QgsAttributeMap`. But I think you are still on it so I won't mind you with details. Tell me if I should have a look at such things.

**Comment by signedav** [comment]
And I think the "Select on Map" (in the screencast) is not yet integrated, right?

**Comment by domi4484** [comment]
Thanks for the feedback!

> Eg. `feature_list` is not defined. I guess it's `linkedFeatures`.
> 
> Another is that it couldn't get the `QgsAttributeMap`.

This two are probably happening when using n:m relations, i tested only with 1:n till now.


> And I think the "Select on Map" (in the screencast) is not yet integrated, right?

Exactly it is still not implemented

**Comment by domi4484** [comment]
> Eg. `feature_list` is not defined. I guess it's `linkedFeatures`.
> 
> Another is that it couldn't get the `QgsAttributeMap`.

This two errors are addressed and automatically tested

**Pull request merged**
